spring:
  application:
    name: "token-test"

jwt:
  secret-key: "1q2w3e4r5t6y7u8i9o0p1q2w3e4r5t6y7u8i9o0p"
  expiration: 60000
  refresh-token:
    expriation: 604800000

  server:
    error:
      whitelabel:
        enabled: false
